Repository hmrc/childcare-calculator-frontend, pull requests merged in 2018-03, with the labels that each got.

#296 Ccalc 3832
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildcarePayFrequencyController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoHasChildcareCostsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/ChildcareNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswers.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/DataHelpers.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildcarePayFrequencyControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoHasChildcareCostsControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/ChildcareNavigatorSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswersSpec.scala
Labels: test completed

#295 CCALC-4094 - input type updated to resolve issue raised by DAC
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_date.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_number.scala.html
Labels: review completed

#297 CCALC - 4080 Remove childcare voucher guidance
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhatToTellTheCalculatorViewSpec.scala
Labels: in review

#298 Ccalc 4029: Create scaffold for 'Did you get the same income for the previous year? screen
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YouGetSameIncomePreviousYearController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/identifiers/YouGetSameIncomePreviousYearId.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CheckYourAnswersHelper.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswers.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/youGetSameIncomePreviousYear.scala.html
  conf/app.routes
  conf/messages.en
  migrations/applied_migrations/YouGetSameIncomePreviousYear.sh
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YouGetSameIncomePreviousYearControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/YouGetSameIncomePreviousYearViewSpec.scala
Labels: review completed

#299 updated the validation message
  conf/messages.en
Labels: review completed

#301 CCALC-4076 - update tc warning message
  app/assets/stylesheets/childcarecalculatorfrontend-app.scss
  conf/messages.en
Labels: review completed

#302 CCALC - 4070 Non eligibility msg for Tax credit on Results page
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModel.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsService.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/TCSchemeInEligibilityMsgBuilder.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/scheme_result.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsServiceSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/TCSchemeInEligibilityMsgBuilderSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultNotEligibleViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/SchemeResultViewSpec.scala
Labels: in review, test completed

#305 CCALC-4095 change in circumstances content and test updated
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala
Labels: review completed, test completed

#307 Ccalc 4100
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursInfoController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursResultController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHousehold.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcare.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursResult.scala.html
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursResultControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcareSpec.scala
Labels: review completed, test completed

#308 Ccalc 4038
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CacheMapCloner.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/CacheMapClonerSpec.scala
Labels: review completed

#304 added in the content for your estimates and the changes in your income
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala
Labels: in review

#306 CCALC - 4081 Employment Income pages validation
  app/uk/gov/hmrc/childcarecalculatorfrontend/FrontendAppConfig.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/EmploymentIncomeCYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentEmploymentIncomeCYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerEmploymentIncomeCYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/EmploymentIncomeCYForm.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/EmploymentIncomePYForm.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/ParentEmploymentIncomeCYForm.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/ParentEmploymentIncomePYForm.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerEmploymentIncomeCYForm.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerEmploymentIncomePYForm.scala
  conf/application.conf
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/EmploymentIncomeCYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentEmploymentIncomeCYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentEmploymentIncomePYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerEmploymentIncomeCYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/EmploymentIncomeCYFormSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/EmploymentIncomePYFormSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/ParentEmploymentIncomeCYFormSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/ParentEmploymentIncomePYFormSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerEmploymentIncomeCYFormSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerEmploymentIncomePYFormSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ParentEmploymentIncomeCYViewSpec.scala
Labels: in review

#310 CCALC - 3837 Considering eligibility and Navigation change for benefit page
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/TaxCredits.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/TaxCreditsSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
Labels: test completed

#313 content and test updated
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhatToTellTheCalculatorViewSpec.scala
Labels: in review, test completed

#314 content and test updates
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/doYouLiveWithPartner.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/DoYouLiveWithPartnerViewSpec.scala
Labels: in review

#312 Ccalc 4093
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/TCSchemeInEligibilityMsgBuilder.scala
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/TCSchemeInEligibilityMsgBuilderSpec.scala
Labels: review completed, test completed

#317 Ccalc 4116: Change content about answering questions on 'Your income for the previous year' screen
  conf/messages.en
Labels: test completed

#318 Ccalc 4041 - scaffold created and content updated
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/BothGetSameIncomePreviousYearController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/identifiers/BothGetSameIncomePreviousYearId.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CheckYourAnswersHelper.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswers.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothGetSameIncomePreviousYear.scala.html
  conf/app.routes
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/BothGetSameIncomePreviousYearControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothGetSameIncomePreviousYearViewSpec.scala
Labels: test completed

#319 CCALC-4092: 2yr old messages added for Scotland and Wales
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModel.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsService.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/aboutYourResults.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultEligible.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourResultsControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModelSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoServiceSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsServiceSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/AboutYourResultsViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultEligibleViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultNotEligibleViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala
Labels: review completed, test completed

#321 5 minutes text added
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhatToTellTheCalculatorViewSpec.scala
Labels: review completed, test completed

#315 Ccalc 4052 : Validation in 'How much will you get paid this year' screen if user previously stated they earn less than £100,000 a year
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/EmploymentIncomeCYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentEmploymentIncomeCYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerEmploymentIncomeCYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/EmploymentIncomeCYForm.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/FormErrorHelper.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerEmploymentIncomeCYForm.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/Enums.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AreYouInPaidWorkControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/EmploymentIncomeCYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentEmploymentIncomeCYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerEmploymentIncomeCYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/EmploymentIncomeCYFormSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/FormErrorHelperSpec.scala
Labels: test completed

#333 fixing build
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/BothGetSameIncomePreviousYearControllerSpec.scala
Labels: review completed

#335 Ccalc 4151 - Changing navigation for "Is your previous income same as this year"
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/EmploymentIncomeNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/IncomeInfoNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/OtherIncomeNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourIncomeInfoPY.scala.html
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/EmploymentIncomeNavigationSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/IncomeInfoNavigationSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/OtherIncomeNavigatorSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourIncomeInfoPYViewSpec.scala
Labels: review completed, test completed

#336 Ccalc 4143: Merging results page into one
  app/uk/gov/hmrc/childcarecalculatorfrontend/cascadeUpserts/MinimumHoursCascadeUpsert.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModel.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MinimumHoursNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsService.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/FirstParagraphBuilder.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultEligible.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/cascadeUpserts/MinimumHoursCascadeUpsertSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourResultsControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModelSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MinimumHoursNavigatorSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoServiceSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsServiceSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/FirstParagraphBuilderSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/TCSchemeInEligibilityMsgBuilderSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/AboutYourResultsViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultEligibleViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultNotEligibleViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala
Labels: review completed, test completed

#340 Ccalc 4154 - Adding Your income summary
  app/assets/stylesheets/childcarecalculatorfrontend-app.scss
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/BothGetSameIncomePreviousYearController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YouGetSameIncomePreviousYearController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CacheMapCloner.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/IncomeSummary.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothGetSameIncomePreviousYear.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/youGetSameIncomePreviousYear.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/BothGetSameIncomePreviousYearControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YouGetSameIncomePreviousYearControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/IncomeSummarySpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothGetSameIncomePreviousYearViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/YouGetSameIncomePreviousYearViewSpec.scala
Labels: review completed

#338 added links to progressive reveals sitewide
  app/assets/stylesheets/childcarecalculatorfrontend-app.scss
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/detail_summary.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/scheme_result.scala.html
Labels: in test

#353 CCALC-4125 - corrected eligibility to allow user to continue on journey if eligible for vouchers when have or could in future childcare costs
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcare.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcareSpec.scala
Labels: in review
