Repository hmrc/childcare-calculator-frontend, pull requests merged in 2018-02, with the labels that each got.

#274 Ccalc 4031
  conf/messages.en
Labels: review completed

#277 Logging feedback
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourChildController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourResultsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildApprovedEducationController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildStartEducationController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildcarePayFrequencyController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildrenDisabilityBenefitsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ExpectedChildcareCostsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryPayBeforeTaxController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryPayPerWeekController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryStartDateController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryWeeksController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/RegisteredBlindController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichChildrenBlindController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichChildrenDisabilityController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichDisabilityBenefitsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoHasChildcareCostsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryPayBeforeTaxController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryPayPerWeekController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryStartDateController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryWeeksController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/actions/DataRequiredAction.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/ChildcareNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/IncomeInfoNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/OtherIncomeNavigator.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/SessionExpiredRouter.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/Utils.scala
Labels: review completed

#278 adding temporary session and url tracking
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/actions/DataRetrievalAction.scala
Labels: review completed

#280 adding uri when no data available
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourChildController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourResultsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildApprovedEducationController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildStartEducationController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildcarePayFrequencyController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildrenDisabilityBenefitsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ExpectedChildcareCostsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryPayBeforeTaxController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryPayPerWeekController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryStartDateController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryWeeksController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/RegisteredBlindController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichChildrenBlindController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichChildrenDisabilityController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichDisabilityBenefitsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoHasChildcareCostsController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryPayBeforeTaxController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryPayPerWeekController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryStartDateController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryWeeksController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/actions/DataRequiredAction.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/SessionExpiredRouter.scala
Labels: review completed

#281 adding session
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/actions/DataRequiredAction.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/SessionExpiredRouter.scala
Labels: review completed

#284 CCALC - 4032 'Not sure' in ESC should not show 'still to check' vouchers on 30 free hours page
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/MaxFreeHoursInfoController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcare.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/maxFreeHoursInfo.scala.html
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/MaxFreeHoursInfoControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcareSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/MaxFreeHoursInfoViewSpec.scala
Labels: review completed

#285 Ccalc 3981
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/BenefitsIncomeCYForm.scala
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/BenefitsIncomeCYFormSpec.scala
Labels: question, test completed

#286 Ccalc 4068
  app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
Labels: review completed, test completed

#287 Ccalc 4004 : Missing content in previous year Pension screen
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/BothPaidPensionPYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerPaidPensionPYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YouPaidPensionPYController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothPaidPensionPY.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerPaidPensionPY.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/youPaidPensionPY.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/BothPaidPensionPYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerPaidPensionPYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YouPaidPensionPYControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothPaidPensionPYViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerPaidPensionPYViewSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/YouPaidPensionPYViewSpec.scala
Labels: review completed

#288 Ccalc 3988: Validation missing from Partner Pension (PY) screen
  app/uk/gov/hmrc/childcarecalculatorfrontend/forms/HowMuchPartnerPayPensionPYForm.scala
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/forms/HowMuchPartnerPayPensionPYFormSpec.scala
Labels: review completed, test completed

#289 removing cachemap logging
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/SessionExpiredRouter.scala
Labels: review completed

#290 Ccalc 3894
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/utils/SessionExpiredRouter.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/utils/SessionExpiredRouterSpec.scala
Labels: review completed

#293 Ccalc 3815
  app/uk/gov/hmrc/childcarecalculatorfrontend/FrontendAppConfig.scala
  project/FrontendBuild.scala
  project/plugins.sbt
Labels: review completed

#294 CCALC-4051 - result page merge, content and how schemes work together update
  app/assets/stylesheets/childcarecalculatorfrontend-app.scss
  app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultController.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModel.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoService.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsService.scala
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/aboutYourResults.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/scheme_result.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
  app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultEligible.scala.html
  conf/messages.en
  test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultControllerSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModelSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoServiceSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsServiceSpec.scala
  test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala
Labels: review completed
